### ISSUE TITLE
Hackathon plans

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/tls-warning-collector#35]
As for Monday hackathon: I'm at your service with my knowledge and ideas to attempt to solve any issues. However, I'd like you to take the initiative and choose 1) what to discuss/solve and 2) in what order (that means choosing the priority). It's, of course, no problem to ask which issue I see as more important, but you'll need to ask :-).

If you manage to get a list of issues to discuss in this issue before Monday, that would be great as I'd have some time for preparation. But if not, no worries.

**Comment by filipgontko-zz** [comment]
Hi Martin, 
I was thinking about the issues and I solved couple of them already so I would like to know your ideas about priorities. I think that Firefox and Chromium are almost stable. (Almost because sometimes the browser is not properly uninstalled. Don't know why though. - but it happend to one or two versions from all firefox and chromium). I will try to fix Opera issues as well. Then we could maybe take a look at the AppVeyor. How do you see it? What do you see as a priority?

**Comment by mukrop** [comment]
Hi. It's in much better shape than before, good work! Last time I spent hours to get at least some screenshots, this time I got 52 Firefox versions and 15 Chromium versions working out of the box (yet no Chrome or Opera).

I don't really have a preference here -- both fixing bugs and AppVeyor are reasonable. If you have bugs you did not succeed to fix, we can discuss those.

**Comment by filipgontko-zz** [comment]
Done.
